/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    Calculate calc = new Calculate();
    calc.sentens1(2, 3);
    calc.sentens2(1, 10);
  }
}
